<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Marraia.Notifications" Version="2.0.0" />
    <PackageReference Include="MassTransit" Version="8.4.1" />
    <PackageReference Include="RabbitMQ.Client" Version="7.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Adapter.Email\Adapter.Email.csproj" />
    <ProjectReference Include="..\..\Adapters\Adapter.Stock.Sync\Adapter.Stock.Sync.csproj" />
    <ProjectReference Include="..\PetShoes.Order.Domain\PetShoes.Order.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MyProfit.Foundation.Redis">
      <HintPath>..\..\References\MyProfit.Foundation.Redis.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
