<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Adapter.Email\Adapter.Email.csproj" />
    <ProjectReference Include="..\PetShoes.Order.Application\PetShoes.Order.Application.csproj" />
    <ProjectReference Include="..\PetShoes.Order.Infrastructure.Repositories\PetShoes.Order.Infrastructure.Repositories.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MyProfit.Foundation.Redis">
      <HintPath>..\..\References\MyProfit.Foundation.Redis.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
